const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{unnamed: 0},
	{ТвердеТіло: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{hpBoss: 0},
	{Спрайт3: 0},
	{Платформер: 0},
	{BoundTo: 0},
	{Спрайт4: 0},
	{Спрайт6: 0},
	{Спрайт5: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Текст: 0},
	{giftbox: 0},
	{Спрайт10: 0},
	{спавнер: 0},
	{daedZone: 0},
	{телепорт: 0},
	{Прикріплення: 0},
	{Спрайт11: 0},
	{Спрайт12: 0},
	{Миша: 0},
	{Куля: 0},
	{Спрайт13: 0},
	{Спрайт14: 0},
	{Спрайт15: 0},
	{Спрайт16: 0},
	{Спрайт17: 0},
	{Спрайт18: 0},
	{Спрайт19: 0},
	{Дотик: 0},
	{Браузер: 0},
	{Спрайт20: 0},
	{Спрайт21: 0},
	{bread: 0},
	{инт: 0},
	{нгор: 0}
];

self.InstanceType = {
	unnamed: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	giftbox: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	спавнер: class extends self.ISpriteInstance {},
	daedZone: class extends self.ISpriteInstance {},
	телепорт: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Миша: class extends self.IInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Дотик: class extends self.IInstance {},
	Браузер: class extends self.IInstance {},
	Спрайт20: class extends self.ISpriteInstance {},
	Спрайт21: class extends self.ISpriteInstance {}
}